import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Ayunis Core Documentation Sidebar
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar (excludes api-reference folder)
  docsSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
  
  // API Reference sidebar (generated by OpenAPI plugin)
  apiSidebar: require('./en/docusaurus-plugin-content-docs/current/api-reference/sidebar.ts').default,
};

export default sidebars;
