import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebar: SidebarsConfig = {
  apisidebar: [
    {
      type: "doc",
      id: "api-reference/ayunis-core-api",
    },
    {
      type: "category",
      label: "app",
      items: [
        {
          type: "doc",
          id: "api-reference/app-controller-is-cloud",
          label: "Check if the deployment is running in a cloud environment",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "models",
      items: [
        {
          type: "doc",
          id: "api-reference/models-controller-get-available-models-with-config",
          label: "Get all available models",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-create-permitted-model",
          label: "Create a permitted model",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-delete-permitted-model",
          label: "Delete a permitted model",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-get-permitted-language-models",
          label: "Get all permitted language models",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-get-effective-default-model",
          label: "Get the effective default model for the user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-get-org-specific-default-model",
          label: "Get the organization default model",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-manage-org-default-model",
          label: "Set or update the organization default model",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-get-user-specific-default-model",
          label: "Get the user-specific default model",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-manage-user-default-model",
          label: "Set or update the user default model",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-delete-user-default-model",
          label: "Delete the user default model",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-get-model-provider-info",
          label: "Get model provider information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-create-permitted-provider",
          label: "Create a permitted provider (Admin only)",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-get-all-permitted-providers",
          label: "Get all permitted providers",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-delete-permitted-provider",
          label: "Delete a permitted provider (Admin only)",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-get-all-model-provider-infos-with-permitted-status",
          label: "Get all model provider infos with permitted status (Admin only)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/models-controller-is-embedding-model-enabled",
          label: "Check if an embedding model is enabled for this org",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "Users",
      items: [
        {
          type: "doc",
          id: "api-reference/user-controller-get-users-in-organization",
          label: "Get users in current organization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/user-controller-update-user-role",
          label: "Update user role",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/user-controller-update-user-name",
          label: "Update user name",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/user-controller-update-password",
          label: "Update user password",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/user-controller-confirm-email",
          label: "Confirm user email",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/user-controller-resend-email-confirmation",
          label: "Resend email confirmation",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/user-controller-delete-user",
          label: "Delete a user",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/user-controller-forgot-password",
          label: "Trigger password reset",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/user-controller-reset-password",
          label: "Reset password with token",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "threads",
      items: [
        {
          type: "doc",
          id: "api-reference/threads-controller-create",
          label: "Create a new thread",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/threads-controller-find-all",
          label: "Get all threads for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/threads-controller-find-one",
          label: "Get a thread by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/threads-controller-delete",
          label: "Delete a thread",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/threads-controller-update-model",
          label: "Update thread model",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/threads-controller-update-agent",
          label: "Update thread agent",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/threads-controller-remove-agent",
          label: "Remove agent from thread",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/threads-controller-get-thread-sources",
          label: "Get all sources for a thread",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/threads-controller-add-file-source",
          label: "Add a file source to a thread",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/threads-controller-remove-source",
          label: "Remove a source from a thread",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/threads-controller-download-source",
          label: "Download a data source as CSV",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "agents",
      items: [
        {
          type: "doc",
          id: "api-reference/agents-controller-create",
          label: "Create a new agent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/agents-controller-find-all",
          label: "Get all agents for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/agents-controller-find-one",
          label: "Get an agent by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/agents-controller-update",
          label: "Update an agent",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/agents-controller-delete",
          label: "Delete an agent",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/agents-controller-get-agent-sources",
          label: "Get all sources for an agent",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/agents-controller-add-file-source",
          label: "Add a file source to an agent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/agents-controller-remove-source",
          label: "Remove a source from an agent",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/agents-controller-assign-mcp-integration",
          label: "Assign MCP integration to agent",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/agents-controller-unassign-mcp-integration",
          label: "Unassign MCP integration from agent",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/agents-controller-list-agent-mcp-integrations",
          label: "List MCP integrations assigned to agent",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "mcp-integrations",
      items: [
        {
          type: "doc",
          id: "api-reference/mcp-integrations-controller-create-predefined",
          label: "Create a new predefined MCP integration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/mcp-integrations-controller-create-custom",
          label: "Create a new custom MCP integration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/mcp-integrations-controller-list",
          label: "List all MCP integrations for organization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/mcp-integrations-controller-list-predefined-configs",
          label: "List available predefined MCP integration configurations",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/mcp-integrations-controller-list-available",
          label: "List all available (enabled) MCP integrations for organization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/mcp-integrations-controller-get-by-id",
          label: "Get MCP integration by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/mcp-integrations-controller-update",
          label: "Update MCP integration",
          className: "api-method patch",
        },
        {
          type: "doc",
          id: "api-reference/mcp-integrations-controller-delete",
          label: "Delete MCP integration",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/mcp-integrations-controller-enable",
          label: "Enable MCP integration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/mcp-integrations-controller-disable",
          label: "Disable MCP integration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/mcp-integrations-controller-validate",
          label: "Validate MCP integration connection",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "retrievers",
      items: [
        {
          type: "doc",
          id: "api-reference/url-retriever-controller-retrieve-url",
          label: "Retrieve content from a URL",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "runs",
      items: [
        {
          type: "doc",
          id: "api-reference/runs-controller-send-message",
          label: "Send a message and receive streaming response",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "subscriptions",
      items: [
        {
          type: "doc",
          id: "api-reference/subscriptions-controller-get-subscription",
          label: "Get subscription details for the current organization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/subscriptions-controller-create-subscription",
          label: "Create a new subscription for the current organization",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/subscriptions-controller-cancel-subscription",
          label: "Cancel the subscription for the current organization",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/subscriptions-controller-has-active-subscription",
          label: "Check if the current organization has an active subscription",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/subscriptions-controller-get-current-price",
          label: "Get the current price per seat monthly",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/subscriptions-controller-update-seats",
          label: "Update the number of seats for the current organization",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/subscriptions-controller-update-billing-info",
          label: "Update the billing information for the current organization",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/subscriptions-controller-uncancel-subscription",
          label: "Uncancel the subscription for the current organization",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "invites",
      items: [
        {
          type: "doc",
          id: "api-reference/invites-controller-create",
          label: "Create a new invite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/invites-controller-get-invites",
          label: "Get all invites for current user's organization",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/invites-controller-get-invite-by-token",
          label: "Get a single invite by token",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/invites-controller-accept-invite",
          label: "Accept an invite",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/invites-controller-delete-invite",
          label: "Delete an invite",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Admin Usage",
      items: [
        {
          type: "doc",
          id: "api-reference/usage-controller-get-usage-config",
          label: "Get usage dashboard configuration",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/usage-controller-get-usage-stats",
          label: "Get overall usage statistics",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/usage-controller-get-provider-usage",
          label: "Get usage statistics by provider",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/usage-controller-get-provider-usage-chart",
          label: "Get provider usage time series aligned by date (chart-ready)",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/usage-controller-get-model-distribution",
          label: "Get usage distribution by model",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/usage-controller-get-user-usage",
          label: "Get usage statistics by user",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "storage",
      items: [
        {
          type: "doc",
          id: "api-reference/storage-controller-upload-file",
          label: "StorageController_uploadFile",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/storage-controller-get-file",
          label: "StorageController_getFile",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/storage-controller-delete-file",
          label: "StorageController_deleteFile",
          className: "api-method delete",
        },
        {
          type: "doc",
          id: "api-reference/storage-controller-get-presigned-url",
          label: "StorageController_getPresignedUrl",
          className: "api-method get",
        },
      ],
    },
    {
      type: "category",
      label: "prompts",
      items: [
        {
          type: "doc",
          id: "api-reference/prompts-controller-create",
          label: "Create a new prompt",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/prompts-controller-find-all",
          label: "Get all prompts for the current user",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/prompts-controller-find-one",
          label: "Get a prompt by ID",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/prompts-controller-update",
          label: "Update a prompt",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/prompts-controller-delete",
          label: "Delete a prompt",
          className: "api-method delete",
        },
      ],
    },
    {
      type: "category",
      label: "Authentication",
      items: [
        {
          type: "doc",
          id: "api-reference/authentication-controller-login",
          label: "User login",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/authentication-controller-register",
          label: "User registration",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/authentication-controller-refresh",
          label: "Refresh authentication tokens",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/authentication-controller-me",
          label: "Get current user information",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/authentication-controller-logout",
          label: "User logout",
          className: "api-method post",
        },
      ],
    },
    {
      type: "category",
      label: "Admin",
      items: [
        {
          type: "doc",
          id: "api-reference/admin-controller-get-all-models",
          label: "AdminController_getAllModels",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/admin-controller-get-model",
          label: "AdminController_getModel",
          className: "api-method get",
        },
        {
          type: "doc",
          id: "api-reference/admin-controller-create-language-model",
          label: "AdminController_createLanguageModel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/admin-controller-create-embedding-model",
          label: "AdminController_createEmbeddingModel",
          className: "api-method post",
        },
        {
          type: "doc",
          id: "api-reference/admin-controller-update-language-model",
          label: "AdminController_updateLanguageModel",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/admin-controller-update-embedding-model",
          label: "AdminController_updateEmbeddingModel",
          className: "api-method put",
        },
        {
          type: "doc",
          id: "api-reference/admin-controller-delete-model",
          label: "AdminController_deleteModel",
          className: "api-method delete",
        },
      ],
    },
  ],
};

export default sidebar.apisidebar;
